language: python
python:
  - "3.4"
install:
  - "pip install -r --reinstall tests_requirements.txt"
  - "pip install python-coveralls"
script:
  - coverage run tests.py --rcfile=.coveragerc -v && coverage report -m && python3.4 tests.py
after_success:
  - coveralls
