from synergine.lib.eint import IncrementedNamedInt

ALIVE = IncrementedNamedInt.get('intelligine.alive')
WALKER = IncrementedNamedInt.get('intelligine.walker')
IMPENETRABLE = IncrementedNamedInt.get('intelligine.impenetrable')
PREVIOUS_DIRECTION = IncrementedNamedInt.get('intelligine.previous_direction')
BLOCKED_SINCE = IncrementedNamedInt.get('intelligine.blocked_since')
ATTACKABLE = IncrementedNamedInt.get('intelligine.attackable')
ATTACKER = IncrementedNamedInt.get('intelligine.attacker')
COLONY = IncrementedNamedInt.get('intelligine.colony')
TRANSPORTABLE = IncrementedNamedInt.get('intelligine.transportable')
TRANSPORTER = IncrementedNamedInt.get('intelligine.transporter')
CARRYING = IncrementedNamedInt.get('intelligine.carrying')
CANT_CARRY_STILL = IncrementedNamedInt.get('intelligine.cantcarry.still')
CANT_PUT_STILL = IncrementedNamedInt.get('intelligine.cantput.still')
ACTION_DIE = IncrementedNamedInt.get('intelligine.basebug.action.die')

COL_ALIVE = IncrementedNamedInt.get('intelligine.col.alive')
COL_WALKER = IncrementedNamedInt.get('intelligine.col.walker')
COL_FIGHTER = IncrementedNamedInt.get('intelligine.col.walker')
COL_TRANSPORTER_CARRYING = IncrementedNamedInt.get('intelligine.col.transporter_carrying')
COL_TRANSPORTER_NOT_CARRYING = IncrementedNamedInt.get('intelligine.col.transporter_not_carrying')