from synergine.lib.eint import IncrementedNamedInt

ALIVE = IncrementedNamedInt.get('intelligine.alive')
WALKER = IncrementedNamedInt.get('intelligine.walker')
IMPENETRABLE = IncrementedNamedInt.get('intelligine.impenetrable')
PREVIOUS_DIRECTION = IncrementedNamedInt.get('intelligine.previous_direction')
BLOCKED_SINCE = IncrementedNamedInt.get('intelligine.blocked_since')
ATTACKABLE = IncrementedNamedInt.get('intelligine.attackable')
ATTACKER = IncrementedNamedInt.get('intelligine.attacker')
COLONY = IncrementedNamedInt.get('intelligine.colony')
TRANSPORTABLE = IncrementedNamedInt.get('intelligine.transportable')
TRANSPORTER = IncrementedNamedInt.get('intelligine.transporter')
CARRYING = IncrementedNamedInt.get('intelligine.carrying')
CANT_CARRY_STILL = IncrementedNamedInt.get('intelligine.cantcarry.still')
CANT_PUT_STILL = IncrementedNamedInt.get('intelligine.cantput.still')
ACTION_DIE = IncrementedNamedInt.get('intelligine.basebug.action.die')

MOVE_MODE_EXPLO = IncrementedNamedInt.get('intelligine.basebug.move.mode.explo')
MOVE_MODE_GOHOME = IncrementedNamedInt.get('intelligine.basebug.move.mode.gohome')

PHEROMON_POSITIONS = IncrementedNamedInt.get('intelligine.phero.positions')
PHEROMON_INFOS = IncrementedNamedInt.get('intelligine.phero.infos')
PHEROMON_DIRECTION = IncrementedNamedInt.get('intelligine.phero.direction')
PHEROMON_DIR_EXPLO = IncrementedNamedInt.get('intelligine.phero.direction.explo')
PHEROMON_DIR_HOME = IncrementedNamedInt.get('intelligine.phero.direction.home')

COL_ALIVE = IncrementedNamedInt.get('intelligine.col.alive')
COL_WALKER = IncrementedNamedInt.get('intelligine.col.walker')
COL_FIGHTER = IncrementedNamedInt.get('intelligine.col.walker')
COL_TRANSPORTER = IncrementedNamedInt.get('intelligine.col.transporter')
COL_TRANSPORTER_CARRYING = IncrementedNamedInt.get('intelligine.col.transporter_carrying')
COL_TRANSPORTER_NOT_CARRYING = IncrementedNamedInt.get('intelligine.col.transporter_not_carrying')
