from synergine.lib.eint import IncrementedNamedInt

ALIVE = IncrementedNamedInt.get('intelligine.alive')
WALKER = IncrementedNamedInt.get('intelligine.walker')
IMPENETRABLE = IncrementedNamedInt.get('intelligine.impenetrable')
ATTACKABLE = IncrementedNamedInt.get('intelligine.attackable')
ATTACKER = IncrementedNamedInt.get('intelligine.attacker')
COLONY = IncrementedNamedInt.get('intelligine.colony')
TRANSPORTABLE = IncrementedNamedInt.get('intelligine.transportable')
TRANSPORTER = IncrementedNamedInt.get('intelligine.transporter')
CARRYING = IncrementedNamedInt.get('intelligine.carrying')
CARRIED = IncrementedNamedInt.get('intelligine.carried')
CANT_CARRY_STILL = IncrementedNamedInt.get('intelligine.cantcarry.still')
CANT_PUT_STILL = IncrementedNamedInt.get('intelligine.cantput.still')
ACTION_DIE = IncrementedNamedInt.get('intelligine.basebug.action.die')
MOLECULE_SEARCHING = IncrementedNamedInt.get('intelligine.molecule_searching')
MOLECULES = IncrementedNamedInt.get('intelligine.molecules')

# TODO: Renommer "move_mode" en "mode" ?
MODE = IncrementedNamedInt.get('intelligine.basebug.move')
MODE_EXPLO = IncrementedNamedInt.get('intelligine.basebug.move.explo')
MODE_GOHOME = IncrementedNamedInt.get('intelligine.basebug.move.gohome')
MODE_NURSE = IncrementedNamedInt.get('intelligine.basebug.move.nurse')
MODE_HOME = IncrementedNamedInt.get('intelligine.basebug.move.home')

MOVE_BYBASS = IncrementedNamedInt.get('intelligine.basebug.move.bypass')
MOVE_BYBASS_DISTANCE = IncrementedNamedInt.get('intelligine.basebug.move.bypass.distance')
MOVE_BYBASS_MEMORY = IncrementedNamedInt.get('intelligine.basebug.move.bypass.memory')
MOVE_BYBASS_WALL = IncrementedNamedInt.get('intelligine.basebug.move.bypass.wall')
MOVE_BYBASS_RE_WALKING = IncrementedNamedInt.get('intelligine.basebug.move.bypass.re_walking')

TYPE = IncrementedNamedInt.get('intelligine.object.type')
TYPE_RESOURCE_EXPLOITABLE = IncrementedNamedInt.get('intelligine.object.type.resource.transformable')
TYPE_RESOURCE_EATABLE = IncrementedNamedInt.get('intelligine.object.type.resource.eatable')
TYPE_NURSERY = IncrementedNamedInt.get('intelligine.object.type.nursery')
TYPE_ANT = IncrementedNamedInt.get('intelligine.object.type.ant')

PHEROMON_POSITIONS = IncrementedNamedInt.get('intelligine.phero.positions')
MOLECULES_INFOS = IncrementedNamedInt.get('intelligine.phero.infos')
MOLECULES_DIRECTION = IncrementedNamedInt.get('intelligine.phero.direction')
PHEROMON_DIR_NONE = IncrementedNamedInt.get('intelligine.phero.direction.none')
PHEROMON_DIR_EXPLO = IncrementedNamedInt.get('intelligine.phero.direction.explo')
EXPLORATION_VECTOR = IncrementedNamedInt.get('intelligine.exploration_vector')

#SMELL = IncrementedNamedInt.get('intelligine.smell')
OBJ_SMELL = IncrementedNamedInt.get('intelligine.obj_smell')
SMELL_FOOD = IncrementedNamedInt.get('intelligine.smell.food')
SMELL_EGG = IncrementedNamedInt.get('intelligine.smell.egg')
POINT_SMELL = IncrementedNamedInt.get('intelligine.point_smell')
POINTS_SMELL = IncrementedNamedInt.get('intelligine.points_smell')

COL_ALIVE = IncrementedNamedInt.get('intelligine.col.alive')
COL_WALKER = IncrementedNamedInt.get('intelligine.col.walker')
COL_FIGHTER = IncrementedNamedInt.get('intelligine.col.walker')
COL_TRANSPORTER = IncrementedNamedInt.get('intelligine.col.transporter')
COL_TRANSPORTER_CARRYING = IncrementedNamedInt.get('intelligine.col.transporter_carrying')
COL_TRANSPORTER_NOT_CARRYING = IncrementedNamedInt.get('intelligine.col.transporter_not_carrying')
COL_EATABLE = IncrementedNamedInt.get('intelligine.col.eatable')
COL_SMELL = IncrementedNamedInt.get('intelligine.col.smell')

BRAIN = IncrementedNamedInt.get('intelligine.brain')
BRAIN_SCHEMA = IncrementedNamedInt.get('intelligine.brain_schema')
BRAIN_PART_MOVE = IncrementedNamedInt.get('intelligine.brain.part.move')
BRAIN_PART_TAKE = IncrementedNamedInt.get('intelligine.brain.part.take')
BRAIN_PART_PUT = IncrementedNamedInt.get('intelligine.brain.part.put')
BRAIN_PART_ATTACK = IncrementedNamedInt.get('intelligine.brain.part.attack')

BODY_SCHEMA = IncrementedNamedInt.get('intelligine.body_schema')
BODY_PART_PHEROMONE_GLAND = IncrementedNamedInt.get('intelligine.body.part.molecule_gland')
